# Generated by Django 5.1.5 on 2025-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_remove_activity_description_activity_athlete_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stream_downloaded',
            field=models.IntegerField(default=0),
        ),
    ]
