# Generated by Django 5.1.5 on 2025-02-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_activity_stream_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='stream_downloaded',
        ),
    ]
