# Generated by Django 5.1.5 on 2025-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_remove_activity_stream_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('activity_id', models.BigIntegerField()),
                ('athlete_id', models.BigIntegerField()),
                ('split_number', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=4, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('hr', models.IntegerField()),
                ('cadence', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
    ]
