# Generated by Django 5.1.5 on 2025-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0005_split_remove_activity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
