# Generated by Django 5.1.5 on 2025-02-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
